### ISSUE TITLE
スケルトンアドオンのテンプレートファイルのエラー

### ISSUE THREAD

**Issue by ivis-yoshida** [RCOSDP/RDM-developer-guide#6]
以下でエラーを確認し、「Save」に置き換えることで正常動作となりました。
※当方での検証は、GakuNin RDMではなくフォーク元のosfを用いて実施しました。
　GakuNin RDMでの実行ならばエラーは起きない可能性がございます。

https://github.com/RCOSDP/RDM-developer-guide/blob/d5ca1e43eedea8a7cc621f671534b0230e8049d8/Skelton/addon/templates/node_settings.mako#L16

**Comment by yacchin1205** [comment]
エラーメッセージを貼っていただいたらreopenさせていただく予定です。一旦クローズします。
